=== isir/greta/bin/Common/Data/xml/behaviorsets.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xsd:include schemaLocation="global.xsd"/>
	
	<xsd:element name="behaviorsets" type="behaviorsetsListType"/>
	
	<xsd:complexType name="behaviorsetsListType">
		<xsd:sequence>
			<xsd:element name="behaviorset" type="behaviorsetType" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="behaviorsetType">
		<xsd:sequence>
			<xsd:element name="signals" type="signalsType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="constraints" type="constraintsType" minOccurs="1" maxOccurs="1"/>	
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="constraintsType">
		<xsd:sequence>
			<xsd:element name="core" type="coreType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="rules" type="rulesType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="coreType">
		<xsd:sequence>
			<xsd:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="implicationType">
		<xsd:sequence>
			<xsd:element name="ifpresent" type="itemType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="thenpresent" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="thennotpresent" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="rulesType">
		<xsd:sequence>
			<xsd:element name="implication" type="implicationType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="signalsType">
		<xsd:sequence>
			<xsd:element name="signal" type="signalType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="itemType">
		<xsd:attribute name="id" type="xsd:integer" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="signalType">
		<xsd:sequence>
			<xsd:element name="alternative" type="alternativeShapeType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:integer" use="required"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="modality" type="parametersetNameType" use="required"/>
		<xsd:attribute name="min" type="xsd:float"/>
		<xsd:attribute name="max" type="xsd:float"/>
		<xsd:attribute name="content" type="xsd:string"/>
		<xsd:attribute name="meaning" type="xsd:string"/>
		<xsd:attribute name="intonation" type="xsd:string"/>
		<xsd:attribute name="voicequality" type="xsd:string"/>
		<xsd:attribute name="excludelist" type="xsd:string"/>
		<xsd:attribute name="repetitivity" type="xsd:integer"/>
		<xsd:attribute name="probability_start" type="xsd:float"/>
		<xsd:attribute name="probability_end" type="xsd:float"/>
	</xsd:complexType>
	
	<xsd:complexType name="alternativeShapeType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="probability" type="xsd:decimal" use="required"/>
		<xsd:attribute name="min" type="xsd:float"/>
		<xsd:attribute name="max" type="xsd:float"/>
		<xsd:attribute name="content" type="xsd:string"/>
		<xsd:attribute name="meaning" type="xsd:string"/>
		<xsd:attribute name="intonation" type="xsd:string"/>
		<xsd:attribute name="voicequality" type="xsd:string"/>
	</xsd:complexType>
</xsd:schema>

=== isir/greta/bin/Common/Data/MultiLayerAttitude/lexicon.xml
<?xml version="1.0" encoding="UTF-8"?>
<behaviorsets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Common/Data/xml/behaviorsets.xsd">

	<!-- PERFORMATIVES -->
	
	<behaviorset name="performative-greet">
		<signals>
			<signal id="1" name="faceexp=greet" modality="face"/>
			<signal id="2" name="iconic=greet_Ges_R" modality="gesture"/>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
			<signal id="4" name="NOD" modality="head"/>
		</signals>
		<constraints>
			<rules>
			</rules>
		</constraints>
	</behaviorset>
	
	<behaviorset name="performative-ask">
		<signals>
			<signal id="1" name="performative=ask_Ges_L" modality="gesture"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="performative-inform">
		<signals>
			<signal id="1" name="performative=inform_Ges_B_Spread" modality="gesture"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="performative-suggest">
		<signals>
			<signal id="1" name="faceexp=suggest" modality="face">
				<alternative name="faceexp=suggest1" probability="0.5"/>
			</signal>
			<signal id="2" name="Aside_Right" modality="head">
        <alternative name="Aside_Left" probability="0.5"/>
      </signal>
			<signal id="3" name="performative=suggest_Ges_L" modality="gesture" min="1.0" max="10.0">	
			</signal>
			
		</signals>
		<constraints>
			<core>
			</core>
		</constraints>
	</behaviorset>
	
	
	<!-- world -->
	
	<behaviorset name="world-person-self">
		<signals>
			<!--signal id="1" name="NOD" modality="head"/-->
			<signal id="2" name="deictic=self_Pos_L" modality="gesture"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="world-place-away">
		<signals>
			<signal id="1" name="LEFT" modality="head"/>
			<signal id="2" name="gaze=look_left" modality="gaze"/>
			<signal id="3" name="deictic=there" modality="gesture"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="world-place-here">
		<signals>
			<signal id="1" name="NOD" modality="head"/>
			<signal id="2" name="adjectival=DEICTIC_RHAND" modality="gesture"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	
	
	<!-- pitchaccent -->
	<behaviorset name="pitchaccent-Hstar">
		<signals>
			<signal id="1" name="DOWN_ASIDE_RIGHT" modality="head">
				<alternative name="nod_middle" probability="0.2"/>
				<alternative name="DOWN_ASIDE_LEFT" probability="0.4"/>
			</signal>
			<signal id="2" name="faceexp=Hstar" modality="face"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="pitchaccent-LplusHstar">
		<signals>
			<signal id="1" name="DOWN_ASIDE_RIGHT" modality="head">
				<alternative name="DOWN_ASIDE_LEFT" probability="0.2"/>
				<alternative name="NOD" probability="0.5"/>
			</signal>
			<signal id="3" name="faceexp=Hstar" modality="face"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="pitchaccent-Lstar">
		<signals>
			<signal id="1" name="NOD" modality="head"/>
			<signal id="2" name="faceexp=Eyebrows_Frown" modality="face"/>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints>
			<rules>
				<implication>
					<ifpresent id="1"/>
					<thenpresent id="3"/>
				</implication>
				<implication>
					<ifpresent id="3"/>
					<thenpresent id="1"/>
				</implication>
			</rules>
		</constraints>
	</behaviorset>
	
	
	<!-- boundary -->
	<behaviorset name="boundary-L">
		<signals>
			<signal id="1" name="DOWN_LEFT" modality="head">
				<alternative name="DOWN_RIGHT" probability="0.3"/>
				<alternative name="DOWN_ASIDE_LEFT" probability="0.1"/>
				<alternative name="DOWN_ASIDE_RIGHT" probability="0.2"/>
				<alternative name="NeutralPosition" probability="0.1"/><!-- head_none -->
			</signal>
			<signal id="2" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="boundary-HL">
		<signals>
			<signal id="1" name="DOWN_LEFT" modality="head">
				<alternative name="DOWN_RIGHT" probability="0.2"/>
				<alternative name="DOWN" probability="0.3"/>
				<alternative name="DOWN_ASIDE_LEFT" probability="0.1"/>
				<alternative name="DOWN_ASIDE_RIGHT" probability="0.1"/>
				<alternative name="head=NeutralPosition" probability="0.1"/><!-- head_none -->
			</signal>
			<signal id="2" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="boundary-H">
		<signals>
			<signal id="1" name="UP_RIGHT" modality="head">
				<alternative name="UP_LEFT" probability="0.3"/>
				<alternative name="UP_ASIDE_LEFT" probability="0.1"/>
				<alternative name="UP_ASIDE_RIGHT" probability="0.2"/>
				<alternative name="head=NeutralPosition" probability="0.1"/><!-- head_none -->
			</signal>
			<signal id="2" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="boundary-HH">
		<signals>
			<signal id="1" name="UP_RIGHT" modality="head">
				<alternative name="UP_LEFT" probability="0.3"/>
				<alternative name="UP_ASIDE_LEFT" probability="0.2"/>
				<alternative name="UP_ASIDE_RIGHT" probability="0.1"/>
				<alternative name="head=NeutralPosition" probability="0.1"/><!-- head_none -->
			</signal>
			<signal id="2" name="faceexp=Eyebrows_Raise" modality="face">
				<alternative name="faceexp=neutral" probability="0.2"/>
			</signal>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="boundary-LL">
		<signals>
			<signal id="1" name="DOWN_LEFT" modality="head">
				<alternative name="DOWN_RIGHT" probability="0.2"/>
				<alternative name="DOWN_ASIDE_LEFT" probability="0.2"/>
				<alternative name="DOWN_ASIDE_RIGHT" probability="0.1"/>
				<alternative name="head=NeutralPosition" probability="0.1"/><!-- head_none -->
			</signal>
			<signal id="2" name="faceexp=Eyebrows_Frown" modality="face">
				<alternative name="faceexp=neutral" probability="0.3"/>
			</signal>
			<signal id="3" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	<behaviorset name="boundary-LH">
		<signals>
			<signal id="1" name="UP_RIGHT" modality="head">
				<alternative name="UP_LEFT" probability="0.3"/>
				<alternative name="UP_ASIDE_LEFT" probability="0.2"/>
				<alternative name="UP_ASIDE_RIGHT" probability="0.1"/>
				<alternative name="head=NeutralPosition" probability="0.1"/><!-- head_none -->
			</signal>  
			<signal id="2" name="gaze=look_at" modality="gaze"/>
		</signals>
		<constraints/>
	</behaviorset>
	
	
</behaviorsets>
