=== isir/greta/bin/Common/Data/xml/gestuary.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xsd:include schemaLocation="global.xsd"/>

<xsd:element name="gestuary" type="gestuaryType"/>

<xsd:complexType name="gestuaryType">
	<xsd:sequence>
		<xsd:element name="gesture" type="gestureType" minOccurs="1" maxOccurs="unbounded"/>		
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="gestureType">
	<xsd:sequence>
		<xsd:element name="phase" type="phaseType" minOccurs="0" maxOccurs="unbounded"/>		
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:string" use="required"/>
	<xsd:attribute name="category" type="xsd:string"/>	
	<xsd:attribute name="hand" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="phaseType">
	<xsd:sequence>
		<xsd:element name="hand" type="handType" minOccurs="0" maxOccurs="2"/>		
	</xsd:sequence>
	<xsd:attribute name="type" type="xsd:string"/>
	<xsd:attribute name="twohanded" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="Trajectory">
	<xsd:sequence>
		<xsd:element name="parameters" type="Parameters" minOccurs="1" maxOccurs="unbounded"/>	
	</xsd:sequence>
	<xsd:attribute name="type" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="Parameters">
	<xsd:attribute name="axis" type="xsd:string" use="required"/>
	<xsd:attribute name="amplitude" type="xsd:float" use="required"/>
	<xsd:attribute name="frequency" type="xsd:float" use="required"/>
	<xsd:attribute name="shift" type="xsd:float" use="required"/>
	<xsd:attribute name="spatialVariation" type="xsd:string" use="required"/>
	<xsd:attribute name="temporalVariation" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="symbolicPositionType">
	<xsd:sequence>
		<xsd:element name="verticalLocation" type="verticalLocationType" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="horizontalLocation" type="horizontalLocationType" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="frontalLocation" type="locationDistanceType" minOccurs="0" maxOccurs="1"/>	
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="uniformPositionType">
	<xsd:attribute name="x" type="xsd:float" default="0"/>
	<xsd:attribute name="y" type="xsd:float" default="0"/>
	<xsd:attribute name="z" type="xsd:float" default="0"/>
</xsd:complexType>

<xsd:simpleType name="touchPositionType">
    <xsd:restriction base="xsd:string">
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="wristOrientationType">
	<xsd:attribute name="global" type="xsd:boolean" default="false"/>
	<xsd:attribute name="w" type="xsd:float" default="0"/>
	<xsd:attribute name="x" type="xsd:float" default="0"/>
	<xsd:attribute name="y" type="xsd:float" default="0"/>
	<xsd:attribute name="z" type="xsd:float" default="0"/>
</xsd:complexType>

<xsd:complexType name="handType">
	<xsd:sequence>
            <xsd:choice>
                <xsd:element name="symbolicPosition" type="symbolicPositionType"/>
                <xsd:element name="uniformPosition" type="uniformPositionType"/>
                <xsd:element name="touchPosition" type="touchPositionType"/>
            </xsd:choice>
		<xsd:element name="handShape" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="wristOrientation" type="wristOrientationType" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
	
	<xsd:attribute name="side" type="xsd:string" use="required"/>
	<xsd:attribute name="openness" type="xsd:float" default="0" />
        
	<xsd:attribute name="verticalFixed" type="xsd:boolean" default="false"/>
	<xsd:attribute name="horizontalFixed" type="xsd:boolean" default="false"/>
	<xsd:attribute name="frontalFixed" type="xsd:boolean" default="false"/>
</xsd:complexType>
	


	<!-- List of direction values. To be completed... -->
    <xsd:simpleType name="directionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="OUTWARD"/>
            <xsd:enumeration value="INWARD"/>
            <xsd:enumeration value="AWAY"/>
            <xsd:enumeration value="TOWARD"/>
            <xsd:enumeration value="UP"/>
            <xsd:enumeration value="DOWN"/>
        </xsd:restriction>
    </xsd:simpleType>
	
    <xsd:simpleType name="verticalLocationType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="YUpperEP"/>
            <xsd:enumeration value="YUpperP"/>
            <xsd:enumeration value="YUpperC"/>
			<xsd:enumeration value="YCC"/>
			<xsd:enumeration value="YLowerC"/>
			<xsd:enumeration value="YLowerP"/>
			<xsd:enumeration value="YLowerEP"/>
			<xsd:enumeration value="YR"/>
        </xsd:restriction>
    </xsd:simpleType>
	<!-- List of values for horizontal location.  -->			
    <xsd:simpleType name="horizontalLocationType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="XEP"/>
            <xsd:enumeration value="XP"/>
            <xsd:enumeration value="XC"/>
            <xsd:enumeration value="XCC"/>
            <xsd:enumeration value="XOppC"/>
			<xsd:enumeration value="XR"/>
        </xsd:restriction>
    </xsd:simpleType>
	<!-- List of values for location distance.  -->	
    <xsd:simpleType name="locationDistanceType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ZNear"/>
            <xsd:enumeration value="ZMiddle"/>
            <xsd:enumeration value="ZFar"/>
			<xsd:enumeration value="ZR"/>
        </xsd:restriction>
    </xsd:simpleType>
	
</xsd:schema>

=== isir/greta/bin/BehaviorRealizer/BehaviorLexicon/gestuary.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestuary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Common/Data/xml/gestuary.xsd">
    <gesture category="_test" id="Bateau_Pos_B">
        <phase>
            <hand openness="1.0" side="LEFT">
                <uniformPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="0.08"/>
                    <verticalLocation fixed="false" overridable="true" value="-0.2"/>
                    <frontalLocation fixed="false" overridable="false" value="0.5"/>
                </uniformPosition>
                <handShape overridable="false" value="FORM_OPEN"/>
                <wristOrientation global="false" overridable="false"
                    w="0.8827765682127073" x="-0.10238216331397239"
                    y="0.3984666858989583" z="0.22682090617588005"/>
            </hand>
            <hand openness="1.0" side="RIGHT">
                <uniformPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="0.08"/>
                    <verticalLocation fixed="false" overridable="true" value="-0.2"/>
                    <frontalLocation fixed="false" overridable="false" value="0.5"/>
                </uniformPosition>
                <handShape overridable="false" value="FORM_OPEN"/>
                <wristOrientation global="false" overridable="false"
                    w="0.8827765682127073" x="-0.10238216331397239"
                    y="-0.3984666858989583" z="-0.22682090617588005"/>
            </hand>
        </phase>
    </gesture>
    <gesture category="_test" id="Micropieux_Ges_B">
        <phase>
            <hand openness="0.6999999999999993" side="LEFT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XC"/>
                    <verticalLocation fixed="false" overridable="false" value="YUpperC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZMiddle"/>
                </symbolicPosition>
                <handShape overridable="false" value="CLOSED_STRAIGHT"/>
                <wristOrientation global="false" overridable="false"
                    w="0.9685831665992737" x="-0.24868988990783691"
                    y="0.0" z="0.0"/>
            </hand>
            <hand openness="0.6999999999999993" side="RIGHT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XC"/>
                    <verticalLocation fixed="false" overridable="false" value="YUpperC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZMiddle"/>
                </symbolicPosition>
                <handShape overridable="false" value="CLOSED_STRAIGHT"/>
                <wristOrientation global="false" overridable="false"
                    w="0.9685831665992737" x="-0.24868988990783691"
                    y="0.0" z="0.0"/>
            </hand>
        </phase>
        <phase>
            <hand openness="0.6999999999999993" side="LEFT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XC"/>
                    <verticalLocation fixed="false" overridable="false" value="YCC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZFar"/>
                </symbolicPosition>
                <handShape overridable="false" value="CLOSED_INSIDE"/>
                <wristOrientation global="false" overridable="false"
                    w="0.9685831665992737" x="-0.24868988990783691"
                    y="0.0" z="0.0"/>
            </hand>
            <hand openness="0.6999999999999993" side="RIGHT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XC"/>
                    <verticalLocation fixed="false" overridable="false" value="YCC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZFar"/>
                </symbolicPosition>
                <handShape overridable="false" value="CLOSED_INSIDE"/>
                <wristOrientation global="false" overridable="false"
                    w="0.9685831665992737" x="-0.24868988990783691"
                    y="0.0" z="0.0"/>
            </hand>
        </phase>
    </gesture>
    <gesture category="_test" id="MonteeDesCrues_Ges_B">
        <phase>
            <hand side="LEFT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XP"/>
                    <verticalLocation fixed="false" overridable="false" value="YLowerEP"/>
                    <frontalLocation fixed="false" overridable="false" value="ZFar"/>
                </symbolicPosition>
                <handShape overridable="false" value="FORM_OPEN"/>
                <wristOrientation global="false" overridable="false"
                    w="0.7803943753242493" x="0.0"
                    y="0.6252875924110413" z="0.0"/>
            </hand>
            <hand side="RIGHT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XP"/>
                    <verticalLocation fixed="false" overridable="false" value="YLowerEP"/>
                    <frontalLocation fixed="false" overridable="false" value="ZFar"/>
                </symbolicPosition>
                <handShape overridable="false" value="FORM_OPEN"/>
                <wristOrientation global="false" overridable="false"
                    w="0.7803943753242493" x="0.0"
                    y="-0.6252875924110413" z="0.0"/>
            </hand>
        </phase>
        <phase>
            <hand side="LEFT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XP"/>
                    <verticalLocation fixed="false" overridable="false" value="YUpperC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZFar"/>
                </symbolicPosition>
                <handShape overridable="false" value="FORM_OPEN"/>
                <wristOrientation global="false" overridable="false"
                    w="0.7997005581855774" x="0.0"
                    y="0.6003990173339844" z="0.0"/>
            </hand>
            <hand side="RIGHT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XP"/>
                    <verticalLocation fixed="false" overridable="false" value="YUpperC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZFar"/>
                </symbolicPosition>
                <handShape overridable="false" value="FORM_OPEN"/>
                <wristOrientation global="false" overridable="false"
                    w="0.7997005581855774" x="0.0"
                    y="-0.6003990173339844" z="0.0"/>
            </hand>
        </phase>
    </gesture>
    <gesture category="_test" id="SousLeMusee_Ges_R">
        <phase>
            <hand openness="0.5" side="RIGHT">
                <uniformPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="0.5"/>
                    <verticalLocation fixed="false" overridable="false" value="0.0"/>
                    <frontalLocation fixed="false" overridable="false" value="0.65"/>
                </uniformPosition>
                <handShape overridable="true" value="FORM_POINT1"/>
                <wristOrientation global="false" overridable="false"
                    w="1.0" x="0.0" y="0.0" z="0.0"/>
            </hand>
        </phase>
        <phase>
            <hand openness="0.3000000000000007" side="RIGHT">
                <uniformPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="0.3"/>
                    <verticalLocation fixed="false" overridable="false" value="-0.2"/>
                    <frontalLocation fixed="false" overridable="false" value="0.65"/>
                </uniformPosition>
                <handShape overridable="true" value="FORM_POINT1"/>
                <wristOrientation global="false" overridable="false"
                    w="0.9239703416824341" x="0.173463836312294"
                    y="0.29342690110206604" z="0.173463836312294"/>
            </hand>
        </phase>
    </gesture>
    <gesture category="beat" id="Beat_Ges_L">
        <phase>
            <hand openness="0.22000000000000064" side="LEFT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XC"/>
                    <verticalLocation fixed="false" overridable="false" value="YCC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZMiddle"/>
                </symbolicPosition>
                <handShape overridable="false" value="BEND_ANGLED"/>
                <wristOrientation global="false" overridable="false"
                    w="0.9381855726242065" x="-0.1783389151096344"
                    y="0.2936151623725891" z="-0.042346853762865067"/>
            </hand>
        </phase>
        <phase>
            <hand openness="0.2400000000000002" side="LEFT">
                <symbolicPosition>
                    <horizontalLocation fixed="false"
                        overridable="false" value="XC"/>
                    <verticalLocation fixed="false" overridable="false" value="YLowerC"/>
                    <frontalLocation fixed="false" overridable="false" value="ZMiddle"/>
                </symbolicPosition>
