=== isir/greta/bin/Common/Data/xml/HeadGestures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="HeadGestures" type="HeadGesturesType"/>

    <xsd:complexType name="HeadGesturesType">
        <xsd:sequence>
            <xsd:element name="head" type="headType" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="headDirectionShift" type="headDirectionShiftType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="headType">
        <xsd:sequence>
            <xsd:element name="KeyPoint" type="KeyPointType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lexeme" type="xsd:string" use="required"/>
        <xsd:attribute name="repetition" type="xsd:integer" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="headDirectionShiftType">
        <xsd:sequence>
            <xsd:element name="VerticalTorsion" type="HeadParamType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="SagittalTilt" type="HeadParamType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="LateralRoll" type="HeadParamType" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="KeyPointType">
        <xsd:sequence>
            <xsd:element name="VerticalTorsion" type="HeadParamType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="SagittalTilt" type="HeadParamType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="LateralRoll" type="HeadParamType" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="HeadParamType">
        <xsd:attribute name="direction" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:float" use="optional"/>
        <xsd:attribute name="max" type="xsd:float" use="optional"/>
    </xsd:complexType>

</xsd:schema>

=== isir/greta/bin/BehaviorRealizer/BehaviorLexicon/HeadGestures_alice.xml
<?xml version="1.0" encoding="UTF-8"?>
<HeadGestures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Common/Data/xml/HeadGestures.xsd">
<!--
	SagittalTilt is an backward/forward rotation in the sagittal plan (around x axis)
	VerticalTorsion is a leftward/rightward rotation around the vertical axis (around y axis)
	LateralRoll is leftward/rightward rotation in the lateral plan (around z axis)
-->

<!-- 
	In the SagittalTilt, the rotation in the backward direction correspond to a backward rotation
						 the rotation in the forward direction correspond to a forward rotation

	In the VerticalTorsion, the rotation in the leftward direction correspond to a leftward rotation
							the rotation in the rightward direction correspond to a rightward rotation

	In the LateralRoll, the rotation in the rightward direction correspond to a rightward rotation
						the rotation in the leftward direction correspond to a leftward rotation

	***for the head gestures (<head>)
	the symbolic value of rotation for SagittalTilt, VerticalTorsion or LateralRoll is defined by : min+spc*(max-min)
		where spc is the spacial parameter (computed at runtime in the interval [0,1])
	To obtain the real value of rotation, the symbolic value must be multiplied by |max_degree| which is defined in the HeadIntervals.xml file (with respect to the human anatomy)

	***for the head postures (<headDirectionShift>)
	the symbolic value of rotation for SagittalTilt, VerticalTorsion or LateralRoll are equal to the corresponding max.
	To obtain the real value of rotation, the symbolic value must be multiplied by |max_degree| which is defined in the HeadIntervals.xml file (with respect to the human anatomy)
-->

	<!-- Used in the lexicon -->

	<head id="Neutral" lexeme="Neutral">
		<KeyPoint>
			<SagittalTilt direction="Backward" min="0.0" max="0.0"/>
			<VerticalTorsion direction="Leftward" min="0.0" max="0.0"/>
			<LateralRoll direction="Leftward" min="0.0" max="0.0"/>
		</KeyPoint>
	</head>

	<head id="Up" lexeme="Up">
		<KeyPoint>
			<SagittalTilt direction="Backward" min="0.15" max="0.15"/>
		</KeyPoint>
	</head>
	<head id="Down" lexeme="Down">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.15" max="0.15"/>
		</KeyPoint>
	</head>
	<head id="Leftward" lexeme="Leftward">
		<KeyPoint>
			<VerticalTorsion direction="Leftward" min="0.10" max="0.10"/>
		</KeyPoint>
	</head>
	<head id="Rightward" lexeme="Rightward">
		<KeyPoint>
			<VerticalTorsion direction="Rightward" min="0.10" max="0.10"/>
		</KeyPoint>
	</head>
	<head id="Nod_Small" lexeme="NOD">
		<KeyPoint type="strokeEnd">
			<SagittalTilt direction="Forward" min="0.05" max="0.1"/>
		</KeyPoint>
	</head>
	<head id="Nod_Middle" lexeme="NOD">
		<KeyPoint type="strokeEnd">
			<SagittalTilt direction="Forward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Nod_Big" lexeme="NOD">
		<KeyPoint type="strokeEnd">
			<SagittalTilt direction="Forward" min="0.1" max="0.4"/>
		</KeyPoint>
	</head>
	<head id="Nod_VeryBig" lexeme="NOD">
		<KeyPoint type="strokeEnd">
			<SagittalTilt direction="Forward" min="0.1" max="0.8"/>
		</KeyPoint>
	</head>
	<head id="Toss_Small" lexeme="TOSS">
		<KeyPoint type="strokeStart">
			<SagittalTilt direction="Backward" min="0.05" max="0.1"/>
		</KeyPoint>
	</head>
	<head id="Toss_Middle" lexeme="TOSS">
		<KeyPoint type="strokeStart">
			<SagittalTilt direction="Backward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Toss_Big" lexeme="TOSS">
		<KeyPoint type="strokeStart">
			<SagittalTilt direction="Backward" min="0.1" max="0.4"/>
		</KeyPoint>
	</head>
	<head id="Toss_VeryBig" lexeme="TOSS">
		<KeyPoint type="strokeStart">
			<SagittalTilt direction="Backward" min="0.1" max="0.8"/>
		</KeyPoint>
	</head>
	<head id="Shake_Middle" lexeme="SHAKE">
		<KeyPoint type="strokeStart">
			<VerticalTorsion direction="Leftward" min="0.05" max="0.2"/>
		</KeyPoint>
		<KeyPoint type="strokeEnd">
			<VerticalTorsion direction="Rightward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Shake_Big" lexeme="SHAKE">
		<KeyPoint type="strokeStart">
			<VerticalTorsion direction="Leftward" min="0.2" max="0.5"/>
		</KeyPoint>
		<KeyPoint type="strokeEnd">
			<VerticalTorsion direction="Rightward" min="0.2" max="0.5"/>
		</KeyPoint>
	</head>
	<head id="Shake_Small" lexeme="SHAKE">
		<KeyPoint type="strokeStart">
			<VerticalTorsion direction="Leftward" min="0.05" max="0.1"/>
		</KeyPoint>
		<KeyPoint type="strokeEnd">
			<VerticalTorsion direction="Rightward" min="0.05" max="0.1"/>
		</KeyPoint>
	</head>
	<head id="Aside_Right" lexeme="Aside_Right">
		<KeyPoint>
			<LateralRoll direction="Rightward" min="0.1" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Aside_Left" lexeme="Aside_Left">
		<KeyPoint>
			<LateralRoll direction="Leftward" min="0.1" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Aside_Right_Reaction" lexeme="Aside_Right_Reaction">
		<KeyPoint>
			<LateralRoll direction="Rightward" min="0.1" max="0.15"/>
		</KeyPoint>
	</head>
	<head id="Aside_Left_Reaction" lexeme="Aside_Left_Reaction">
		<KeyPoint>
			<LateralRoll direction="Leftward" min="0.1" max="0.15"/>
		</KeyPoint>
	</head>
	<head id="Down_Right" lexeme="Down_Right">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.1" max="0.2"/>
			<VerticalTorsion direction="Rightward" min="0.1" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Down_Left" lexeme="Down_Left">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.1" max="0.2"/>
			<VerticalTorsion direction="Leftward" min="0.1" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Up_Right" lexeme="Up_Right">
		<KeyPoint>
			<SagittalTilt direction="Backward" min="0.1" max="0.2"/>
			<VerticalTorsion direction="Rightward" min="0.1" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Up_Left" lexeme="Up_Left">
		<KeyPoint>
			<SagittalTilt direction="Backward" min="0.1" max="0.2"/>
			<VerticalTorsion direction="Leftward" min="0.1" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Up_Aside_Right" lexeme="Up_Aside_Right">
		<KeyPoint>
			<SagittalTilt direction="Backward" min="0.05" max="0.2"/>
			<LateralRoll direction="Rightward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Up_Aside_Left" lexeme="Up_Aside_Left">
		<KeyPoint>
			<SagittalTilt direction="Backward" min="0.05" max="0.2"/>
			<LateralRoll direction="Leftward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Down_Aside_Right" lexeme="Down_Aside_Right">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.05" max="0.2"/>
			<LateralRoll direction="Rightward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="Down_Aside_Left" lexeme="Down_Aside_Left">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.05" max="0.2"/>
			<LateralRoll direction="Leftward" min="0.05" max="0.2"/>
		</KeyPoint>
	</head>

	<!-- Used in MSE -->

	<head id="relief_signal_14" lexeme="RELIEF_SIGNAL">
		<KeyPoint>
			<LateralRoll direction="Rightward" min="0.04" max="0.15"/>
			<SagittalTilt direction="Backward" min="0.04" max="0.15"/>
			<VerticalTorsion direction="Rightward" min="0.04" max="0.15"/> 
		</KeyPoint>
	</head>
	<head id="pride_signal_8" lexeme="PRIDE_SIGNAL">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.04" max="0.15"/>
			<VerticalTorsion direction="Leftward" min="0.07" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="pride_signal_9" lexeme="PRIDE_SIGNAL">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.04" max="0.15"/>
			<VerticalTorsion direction="Rightward" min="0.07" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="embarrassment_signal_1" lexeme="EMBARRASSMENT_SIGNAL">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.15" max="0.5"/>
		</KeyPoint>
	</head>
	<head id="embarrassment_signal_2" lexeme="EMBARRASSMENT_SIGNAL">
		<KeyPoint>
			<VerticalTorsion direction="Leftward" min="0.15" max="0.5"/>
		</KeyPoint>
	</head>
	<head id="joy_signal_7" lexeme="JOY_SIGNAL">
		<KeyPoint>
			<LateralRoll direction="Rightward" min="0.04" max="0.2"/>
			<VerticalTorsion direction="Leftward" min="0.01" max="0.05"/>
		</KeyPoint>
	</head>
	<head id="joy_signal_8" lexeme="JOY_SIGNAL">
		<KeyPoint>
			<LateralRoll direction="Leftward" min="0.04" max="0.2"/>
			<VerticalTorsion direction="Rightward" min="0.01" max="0.05"/>
		</KeyPoint>
	</head>
	<head id="regret_signal_13" lexeme="REGRET_SIGNAL">
		<KeyPoint>
			<LateralRoll direction="Rightward" min="0.04" max="0.2"/>
			<VerticalTorsion direction="Leftward" min="0.01" max="0.05"/>
		</KeyPoint>
	</head>
	<head id="regret_signal_14" lexeme="REGRET_SIGNAL">
		<KeyPoint>
			<LateralRoll direction="Leftward" min="0.04" max="0.2"/>
			<VerticalTorsion direction="Rightward" min="0.01" max="0.05"/>
		</KeyPoint>
	</head>
	<head id="regret_signal_16" lexeme="SHAKE">
		<KeyPoint type="strokeStart">
			<SagittalTilt direction="Forward" min="0.15" max="0.3"/>
			<VerticalTorsion direction="Rightward" min="0.04" max="0.2"/>
		</KeyPoint>
		<KeyPoint type="strokeEnd">
			<SagittalTilt direction="Forward" min="0.15" max="0.3"/>
			<VerticalTorsion direction="Leftward" min="0.04" max="0.2"/>
		</KeyPoint>
	</head>
	<head id="regret_signal_24" lexeme="REGRET_SIGNAL">
		<KeyPoint>
			<SagittalTilt direction="Forward" min="0.1" max="0.25"/>
		</KeyPoint>
	</head>
	<head id="rejoice_signal_14" lexeme="REJOICE_SIGNAL">
		<KeyPoint>
			<LateralRoll direction="Leftward" min="0.04" max="0.2"/>
			<VerticalTorsion direction="Rightward" min="0.01" max="0.05"/>
		</KeyPoint>
	</head>
	<head id="rejoice_signal_13" lexeme="SHAKE">
		<KeyPoint type="strokeStart">
			<VerticalTorsion direction="Rightward" min="0.01" max="0.02"/>
		</KeyPoint>
		<KeyPoint type="strokeEnd">
			<VerticalTorsion direction="Leftward" min="0.01" max="0.02"/>
		</KeyPoint>
	</head>
	<head id="rejoice_signal_20" lexeme="SHAKE">
		<KeyPoint type="strokeStart">
			<VerticalTorsion direction="Rightward" min="0.008" max="0.015"/>
		</KeyPoint>
		<KeyPoint type="strokeEnd">
