=== isir/greta/bin/Common/Data/xml/profiles.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
<!-- useless
<xs:include schemaLocation="global.xsd"/>
-->
<xs:complexType name="parameterType">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:decimal" use="required"/>
	<xs:attribute name="min" type="xs:decimal" default="0.0"/>
	<xs:attribute name="max" type="xs:decimal" default="1.0"/>
</xs:complexType>
		
<xs:complexType name="parsetType">
	<xs:sequence>
		<xs:element name="Parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="parsetsType">
	<xs:sequence>
		<xs:element name="parameter-set" type="parsetType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="profile" type="parsetsType">
</xs:element>

</xs:schema>

=== isir/greta/bin/BehaviorPlanner/Baseline/POPPY.xml
<?xml version="1.0"?>
<profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Common/Data/xml/profiles.xsd">
	<parameter-set name="face">
		<Parameter name="preference" value="0.9"/>
		<Parameter name="OAC" value="0.95"/>
		<Parameter name="SPC" value="0.4" min="-1.0" max="1.0"/>
		<Parameter name="TMP" value="-0.2" min="-1.0" max="1.0"/>
		<Parameter name="FLD" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="PWR" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="REP" value="0.0" min="-1.0" max="1.0"/>
	</parameter-set>
	<parameter-set name="gesture">
		<Parameter name="preference" value="1.0"/>
		<Parameter name="OAC" value="0.95"/>
		<Parameter name="SPC" value="0.00" min="-1.0" max="1.0"/>
		<Parameter name="TMP" value="0.02" min="-1.0" max="1.0"/>
		<Parameter name="FLD" value="1.00" min="-1.0" max="1.0"/>
		<Parameter name="PWR" value="0.6" min="-1.0" max="1.0"/>
		<Parameter name="REP" value="-0.1" min="-1.0" max="1.0"/>
	</parameter-set>
	<parameter-set name="gaze">
		<Parameter name="preference" value="0.9"/>
		<Parameter name="OAC" value="0.95"/>
		<Parameter name="SPC" value="0.4" min="-1.0" max="1.0"/>
		<Parameter name="TMP" value="-0.2" min="-1.0" max="1.0"/>
		<Parameter name="FLD" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="PWR" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="REP" value="0.0" min="-1.0" max="1.0"/>
	</parameter-set>
	<parameter-set name="torso">
		<Parameter name="preference" value="0.9"/>
		<Parameter name="OAC" value="0.95"/>
		<Parameter name="SPC" value="0.4" min="-1.0" max="1.0"/>
		<Parameter name="TMP" value="-0.2" min="-1.0" max="1.0"/>
		<Parameter name="FLD" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="PWR" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="REP" value="0.0" min="-1.0" max="1.0"/>
	</parameter-set>
	<parameter-set name="head">
		<Parameter name="preference" value="0.8"/>
		<Parameter name="OAC" value="0.8"/>
		<Parameter name="SPC" value="0.4" min="-1.0" max="1.0"/>
		<Parameter name="TMP" value="-0.7" min="-1.0" max="1.0"/>
		<Parameter name="FLD" value="0.0" min="-1.0" max="1.0"/>
		<Parameter name="PWR" value="-0.5" min="-1.0" max="1.0"/>
		<Parameter name="REP" value="0.0" min="-1.0" max="1.0"/>
	</parameter-set>
	<parameter-set name="speech">
		<Parameter name="preference" value="1"/>
		<Parameter name="OAC" value="0.4"/>
		<Parameter name="SPC" value="0" min="-1.0" max="1.0"/>
		<Parameter name="TMP" value="0" min="-1.0" max="1.0"/>
		<Parameter name="FLD" value="0" min="-1.0" max="1.0"/>
		<Parameter name="PWR" value="0" min="-1.0" max="1.0"/>
		<Parameter name="REP" value="0" min="-1.0" max="1.0"/>
	</parameter-set>
</profile>
