=== isir/greta/bin/Common/Data/xml/qualifiers.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xs:include schemaLocation="global.xsd"/>

<xs:simpleType name="CollapsedString">
	<xs:restriction base="xs:string">
		<xs:whiteSpace value="collapse"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="modulationType">

	<xs:sequence>
	
		<xs:element name="destination" type="parametersetNameType" minOccurs="1" maxOccurs="1"/>
	
		<xs:element name="parameter" type="parameterNameType" minOccurs="1" maxOccurs="1"/>

		<xs:element name="operator" type="operatorNameType" minOccurs="1" maxOccurs="1"/>
		
		<xs:sequence>
			<xs:choice>
				<xs:sequence>
					<xs:element name="op1_name" type="parametersetNameType"/>
					<xs:element name="op1_attribute" type="parameterNameType"/>
				</xs:sequence>
				<xs:element name="op1_value" type="xs:decimal"/>
			</xs:choice>
		</xs:sequence>
		
		<xs:sequence>
			<xs:choice>
				<xs:sequence>
					<xs:element name="op2_name" type="parametersetNameType" minOccurs="0" maxOccurs="1"/>
					<xs:element name="op2_attribute" type="parameterNameType" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
				<xs:element name="op2_value" type="xs:decimal"/>
			</xs:choice>
		</xs:sequence>
		
		<xs:element name="op3_value" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
		
	</xs:sequence>

</xs:complexType>

<xs:complexType name="qualifierType">
	<xs:sequence>
		<xs:element name="modulation" type="modulationType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>


<xs:complexType name="qualifiersType">
	<xs:sequence>
		<xs:element name="qualifier" type="qualifierType" minOccurs="0" maxOccurs="unbounded">
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:element name="qualifiers" type="qualifiersType">
</xs:element>

</xs:schema>

=== isir/greta/bin/Common/Data/MultiLayerAttitude/BQC/BQCDomSmallIncr.xml
<?xml version="1.0"?>
<qualifiers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Common/Data/xml/qualifiers.xsd">

	<qualifier name="backchannel-liking">
		<modulation>
			<destination>face</destination><parameter>SPC.value</parameter><operator>INTENSIFY</operator>
			<op1_name>face</op1_name><op1_attribute>SPC.value</op1_attribute><!--op2_value>intensity</op2_value-->
		</modulation>
	</qualifier>
	<qualifier name="regulator-touchSelf">
		<modulation>
			<destination>gesture</destination><parameter>FLD.value</parameter><operator>VAL</operator>
			<op1_value>1</op1_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>TMP.value</parameter><operator>VAL</operator>
			<op1_value>0</op1_value>
		</modulation>
	</qualifier>
	<qualifier name="emotion-joy">
		<modulation>
			<destination>gesture</destination><parameter>preference.value</parameter><operator>ADD</operator>
			<op1_name>gesture</op1_name><op1_attribute>preference.value</op1_attribute><op2_value>0.2</op2_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>preference.value</parameter><operator>LIM</operator>
			<op1_name>gesture</op1_name><op1_attribute>preference.min</op1_attribute><op2_name>gesture</op2_name>
			<op2_attribute>preference.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>SPC.value</parameter><operator>ADD</operator>
			<op1_name>gesture</op1_name><op1_attribute>SPC.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>SPC.value</parameter><operator>LIM</operator>
			<op1_name>gesture</op1_name><op1_attribute>SPC.min</op1_attribute><op2_name>gesture</op2_name>
			<op2_attribute>SPC.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>PWR.value</parameter><operator>ADD</operator>
			<op1_name>gesture</op1_name><op1_attribute>PWR.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>PWR.value</parameter><operator>LIM</operator>
			<op1_name>gesture</op1_name><op1_attribute>PWR.min</op1_attribute><op2_name>gesture</op2_name>
			<op2_attribute>PWR.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>TMP.value</parameter><operator>ADD</operator>
			<op1_name>gesture</op1_name><op1_attribute>TMP.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>TMP.value</parameter><operator>LIM</operator>
			<op1_name>gesture</op1_name><op1_attribute>TMP.min</op1_attribute><op2_name>gesture</op2_name>
			<op2_attribute>TMP.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>FLD.value</parameter><operator>ADD</operator>
			<op1_name>gesture</op1_name><op1_attribute>FLD.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>FLD.value</parameter><operator>LIM</operator>
			<op1_name>gesture</op1_name><op1_attribute>FLD.min</op1_attribute><op2_name>gesture</op2_name>
			<op2_attribute>FLD.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>OAC.value</parameter><operator>ADD</operator>
			<op1_name>gesture</op1_name><op1_attribute>OAC.value</op1_attribute><op2_value>0.3</op2_value>
		</modulation>
		<modulation>
			<destination>gesture</destination><parameter>OAC.value</parameter><operator>LIM</operator>
			<op1_name>gesture</op1_name><op1_attribute>OAC.min</op1_attribute><op2_name>gesture</op2_name>
			<op2_attribute>OAC.max</op2_attribute>
		</modulation>
		
		<modulation>
			<destination>face</destination><parameter>preference.value</parameter><operator>ADD</operator>
			<op1_name>face</op1_name><op1_attribute>preference.value</op1_attribute><op2_value>0.4</op2_value>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>preference.value</parameter><operator>LIM</operator>
			<op1_name>face</op1_name><op1_attribute>preference.min</op1_attribute><op2_name>face</op2_name>
			<op2_attribute>preference.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>TMP.value</parameter><operator>ADD</operator>
			<op1_name>face</op1_name><op1_attribute>TMP.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>TMP.value</parameter><operator>LIM</operator>
			<op1_name>face</op1_name><op1_attribute>TMP.min</op1_attribute><op2_name>face</op2_name>
			<op2_attribute>TMP.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>FLD.value</parameter><operator>ADD</operator>
			<op1_name>face</op1_name><op1_attribute>FLD.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>FLD.value</parameter><operator>LIM</operator>
			<op1_name>face</op1_name><op1_attribute>FLD.min</op1_attribute><op2_name>face</op2_name>
			<op2_attribute>FLD.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>SPC.value</parameter><operator>ADD</operator>
			<op1_name>face</op1_name><op1_attribute>SPC.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>SPC.value</parameter><operator>LIM</operator>
			<op1_name>face</op1_name><op1_attribute>SPC.min</op1_attribute><op2_name>face</op2_name>
			<op2_attribute>SPC.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>PWR.value</parameter><operator>ADD</operator>
			<op1_name>face</op1_name><op1_attribute>PWR.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>PWR.value</parameter><operator>LIM</operator>
			<op1_name>face</op1_name><op1_attribute>PWR.min</op1_attribute><op2_name>face</op2_name>
			<op2_attribute>PWR.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>OAC.value</parameter><operator>ADD</operator>
			<op1_name>face</op1_name><op1_attribute>OAC.value</op1_attribute><op2_value>0.3</op2_value>
		</modulation>
		<modulation>
			<destination>face</destination><parameter>OAC.value</parameter><operator>LIM</operator>
			<op1_name>face</op1_name><op1_attribute>OAC.min</op1_attribute><op2_name>face</op2_name>
			<op2_attribute>OAC.max</op2_attribute>
		</modulation>
		
		<modulation>
			<destination>torso</destination><parameter>preference.value</parameter><operator>ADD</operator>
			<op1_name>torso</op1_name><op1_attribute>preference.value</op1_attribute><op2_value>0.3</op2_value>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>preference.value</parameter><operator>LIM</operator>
			<op1_name>torso</op1_name><op1_attribute>preference.min</op1_attribute><op2_name>torso</op2_name>
			<op2_attribute>preference.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>TMP.value</parameter><operator>ADD</operator>
			<op1_name>torso</op1_name><op1_attribute>TMP.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>TMP.value</parameter><operator>LIM</operator>
			<op1_name>torso</op1_name><op1_attribute>TMP.min</op1_attribute><op2_name>torso</op2_name>
			<op2_attribute>TMP.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>FLD.value</parameter><operator>ADD</operator>
			<op1_name>torso</op1_name><op1_attribute>FLD.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>FLD.value</parameter><operator>LIM</operator>
			<op1_name>torso</op1_name><op1_attribute>FLD.min</op1_attribute><op2_name>torso</op2_name>
			<op2_attribute>FLD.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>SPC.value</parameter><operator>ADD</operator>
			<op1_name>torso</op1_name><op1_attribute>SPC.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>SPC.value</parameter><operator>LIM</operator>
			<op1_name>torso</op1_name><op1_attribute>SPC.min</op1_attribute><op2_name>torso</op2_name>
			<op2_attribute>SPC.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>PWR.value</parameter><operator>ADD</operator>
			<op1_name>torso</op1_name><op1_attribute>PWR.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>PWR.value</parameter><operator>LIM</operator>
			<op1_name>torso</op1_name><op1_attribute>PWR.min</op1_attribute><op2_name>torso</op2_name>
			<op2_attribute>PWR.max</op2_attribute>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>OAC.value</parameter><operator>ADD</operator>
			<op1_name>torso</op1_name><op1_attribute>OAC.value</op1_attribute><op2_value>0.3</op2_value>
		</modulation>
		<modulation>
			<destination>torso</destination><parameter>OAC.value</parameter><operator>LIM</operator>
			<op1_name>torso</op1_name><op1_attribute>OAC.min</op1_attribute><op2_name>torso</op2_name>
			<op2_attribute>OAC.max</op2_attribute>
		</modulation>
		
		<modulation>
			<destination>head</destination><parameter>TMP.value</parameter><operator>ADD</operator>
			<op1_name>head</op1_name><op1_attribute>TMP.value</op1_attribute><op2_value>0.5</op2_value>
		</modulation>
		<modulation>
			<destination>head</destination><parameter>TMP.value</parameter><operator>LIM</operator>
